### ISSUE TITLE
Bad Link

### ISSUE THREAD

**Issue by rallenmotional** [okta-samples/okta-express-sample#1]
Hello,
The documentation links to a developer article, which results in a 404 error.
The bad link in the Github README is: https://developer.okta.com/docs/guides/sign-into-web-app/nodeexpress/main/
The correct link is: https://developer.okta.com/docs/guides/sign-into-web-app-redirect/node-express/main/

**Comment by mraible** [comment]
Thank you for reporting this issue @rallenmotional! Fixed in https://github.com/okta-samples/okta-express-sample/commit/ae9e7f2ed26605800827a0494a95cacc946485f3.
