### ISSUE TITLE
Could be more useful with some simple additions

### ISSUE THREAD

**Issue by ophers** [okta-samples/okta-express-sample#2]
This example project is linked to official OKTA developer documentation.
1. If you follow the comments some are about "...I added the "groups" claim - but it's still not visible..."
2. Other comments are about "...how do I get the refresh_token...?"
Here "passport-openidconnect" could do with better documentation. Until then this code can help by demonstrating it.
3. And ... why not show how to leverage self-discovery, namely `/.well-known/openid-configuration`

**Comment by tanay1337** [comment]
Thanks for the suggestions and the PR, @ophers 🙌
