### ISSUE TITLE
Error handling is broken

### ISSUE THREAD

**Issue by ophers** [okta-samples/okta-express-sample#4]
So if the authentication fails - ex. the `CLIENT_SECRET` was mistyped - the user gets this page, instead of a detailed error.
(...as an aside also here passport could do with better documentation)
![image](https://user-images.githubusercontent.com/11839190/185747027-c2217406-e6f5-47b1-b7fc-d9ed7ef50a4f.png)

**Comment by tanay1337** [comment]
Thanks for the suggestion and the PR, @ophers 💪
