### ISSUE TITLE
Invalid Scope at Okta Login

### ISSUE THREAD

**Issue by illimw** [okta-samples/okta-express-sample#6]
I get this error message when logging into Okta - "One or more scopes are not configured for the authorization server resource." All ten listings are for modules in Okta-express-sample-main project, which I downloaded. Is this fixed in the Okta/Security/API/Authorization Server/Scopes settings?

The first item referenced in the error message is Strategy.authenticate in passport-openidconnect/lib. Here is the section in the code that it is pointing to:

Strategy.prototype.authenticate = function(req, options) {
  options = options || {};
  var self = this;

  if (req.query && req.query.error) {
    if (req.query.error == 'access_denied') {
      return this.fail({ message: req.query.error_description });
    } else {
      return this.error(new AuthorizationError(req.query.error_description, req.query.error, req.query.error_uri));
    }
  }
I just noticed that the passport settings include a scope value - scope: 'groups profile offline_access'. Do I need to change this? Changing the scope value to 'openid profile' did it. I'm now able to log into Okta, before getting routed to the profile page. Woot!

**Comment by ophers** [comment]
Hi @illimw, yes this is an issue with the `groups` scope.
You must be using the OKTA **Custom** Authorization Server (as opposed to the OKTA **Org** Authorization Server).
With the **Custom** server the `groups` scope is not defined by default. As you already noted it's done here:
> Is this fixed in the Okta/Security/API/Authorization Server/Scopes settings?

To use the **Org** server set your `OKTA_ISSUER_URI` to `https://{{ YOUR_ORG_URL }}` (remove the `/oauth2/default` suffix).

A note on `scope`:
1. Adding `openid` is redundant as `passport-openidconnect` always prefixes it.
2. Adding `offline_access` will have the Auth Server provide you a `refresh_token`

**Comment by alisaduncan** [comment]
Resolved by #9 to avoid confusion and keep the scopes consistent across the samples.

Thanks for reporting this @illimw !
