### ISSUE TITLE
okta cli installed, account made, everything done, but on running npm start getting this err

### ISSUE THREAD

**Issue by me-imfhd** [okta-samples/okta-express-sample#7]
AxiosError: connect ECONNREFUSED ::1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16) {
  port: 80,
![image](https://github.com/okta-samples/okta-express-sample/assets/114667178/35dfb582-bb78-4e4c-bea2-a94a5c9c6c84)

**Comment by mraible** [comment]
Are you trying to run it on port 80? If so, you might need to stop the other process first. I just tried cloning this repo, running `okta start` in it, and then following the instructions. Everything worked fine for me.

<img width="1186" alt="Screenshot 2023-07-10 at 9 05 29 AM" src="https://github.com/okta-samples/okta-express-sample/assets/17892/5d9de55b-195b-4abe-8731-d51203dc2a80">
<img width="1186" alt="Screenshot 2023-07-10 at 9 05 41 AM" src="https://github.com/okta-samples/okta-express-sample/assets/17892/ee5d3829-3d57-413d-b972-2a214e91c3a6">

**Comment by me-imfhd** [comment]
i can't recall where i was stuck, i was fed up doing so much installation and pasting code, i used auth0 and it ran like butter, most probably i did any step wrong but thanks from the response and effort man!
